# vim:fileencoding=utf-8:foldmethod=marker

clear_all_shortcuts yes
kitty_mod alt+shift
map_timeout 2.0

enabled_layouts fat:bias=70;full_size=1;mirrored=false, tall:bias=50;full_size=1;mirrored=false, stack

# layout modification
map alt+space>n next_layout
map alt+space>m move_window_to_top
#map ctrl+[ layout_action decrease_num_full_size_windows
#map ctrl+] layout_action increase_num_full_size_windows
map alt+r layout_action bias 50 60 70 80
map alt+space>r layout_action bias 50 60 70 80
map alt+space>f toggle_layout stack
map alt+f toggle_layout stack

# windows focus
map alt+space>j next_window
map alt+j next_window
map alt+space>k previous_window
map alt+k previous_window
map alt+space>h previous_window
map alt+h previous_window
map alt+space>l next_window
map alt+l next_window
map alt+space>. focus_visible_window
map alt+. focus_visible_window

#window modification
#map alt+space>enter new_window
#map alt+enter new_window
map alt+space>enter launch --cwd=current
map alt+enter launch --cwd=current
map alt+space>u close_window
map alt+q close_window
map alt+space>y swap_with_window
map alt+y swap_with_window
map alt+space>shift+y detach_window ask
map alt+shift+y detach_window ask

#tab focus
map alt+space>shift+. select_tab
map alt+shift+. select_tab
map alt+space>shift+l next_tab
map alt+shift+l next_tab
map alt+space>shift+h previous_tab
map alt+shift+h previous_tab

#tab modify
map alt+space>c new_tab
map alt+c new_tab
map alt+space>shift+q close_tab
map alt+shift+q close_tab
tab_switch_strategy left
map alt+space>, set_tab_title
map alt+, set_tab_title
map alt+space>shift+u detach_tab ask
map alt+shift+u detach_tab ask
map alt+ctrl+shift+h move_tab_backward
map alt+ctrl+shift+l move_tab_forward

#command palette
map alt+space>alt+space command_palette
map alt+? command_palette
map alt+space>? command_palette

# BEGIN_KITTY_THEME
# Night Lion V1
include current-theme.conf
# END_KITTY_THEME
background_opacity 0.8

tab_bar_edge top
tab_bar_style slant

# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# TODO SCROLLING / COPY PASTE
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard


# TODO SESSION
