#!/bin/bash
# Start a timer displayed in the terminal
# See example of usage in "stopwatch"

date1=$(date +%s)
while true; do
	echo -ne "$(date -u --date @$(($(date +%s) - $date1)) +%H:%M:%S)\r"
	sleep 0.1
done
