#! /usr/bin/env bash

case "$(printf "kill\nzzz\nreboot\nshutdown" | $DMENU -i -c -l 4)" in
	kill) ps -u $USER -o pid,comm,%cpu,%mem \
		| $DMENU -i -c -l 10 -p Kill: \
		| awk '{print $1}' \
		| xargs -r kill ;;
	zzz) loginctl lock-session ; systemctl suspend -i ;;
	reboot) systemctl reboot -i ;;
	shutdown) systemctl poweroff ;;
	*) exit 1 ;;
esac
